//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Propriety
    {

        public Propriety()
        {

        }

        public Propriety(int id, DateTime dataCreated, string eve, string people, string landscapes, string photoplace)
        {
            this.Id = id;
            this.DataCreated = dataCreated;
            this.Event = eve;
            this.People = people;
            this.Landscapes = landscapes;
            this.Photoplace = photoplace;
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public System.DateTime DataCreated { get; set; }
        [DataMember]
        public string Event { get; set; }
        [DataMember]
        public string People { get; set; }
        [DataMember]
        public string Landscapes { get; set; }
        [DataMember]
        public string Photoplace { get; set; }
        [DataMember]
        public virtual File File { get; set; }
    }
}
