//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.DynamicProprieties = new HashSet<DynamicPropriety>();
        }

        public File(int id, string fullPath, bool isPhoto, bool isDeleted, Propriety propriety)
        {
            this.Id = id;
            this.FullPath = fullPath;
            this.IsPhoto = isPhoto;
            this.IsDeleted = isDeleted;
            this.Propriety = propriety;
        }

        public void AddDynamicProp(DynamicPropriety prop)
        {
            this.DynamicProprieties.Add(prop);
        }

        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string FullPath { get; set; }
        [DataMember]
        public bool IsPhoto { get; set; }
        [DataMember]
        public bool IsDeleted { get; set; }

        [DataMember]
        public virtual Propriety Propriety { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [DataMember]
        public virtual ICollection<DynamicPropriety> DynamicProprieties { get; set; }
    }
}
